
name: Continuous
on: 
  - push

jobs:

  AppImage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['bionic', 'xenial']
    container:
      image: srevinsaju/appimagetestenv-${{ matrix.container }}
    steps:
      - name: Setup up User
        run: |
          apt update
          apt install -y sudo
          echo "github ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          useradd -m github
          usermod -aG sudo github
          su - github
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 
      - name: Detect the newly added apps
        run: |
          # show the changed files
          # sudo bash code/prep-dummy-soundcard.sh
          echo "Detected changes in the following files"
          set +x
          git pull origin master
          git -P log | grep $GITHUB_SHA
          git diff --name-only $GITHUB_SHA origin/master | grep data 
          FILES="$(git diff --name-only $GITHUB_SHA origin/master | grep data | tail -n 1)"
          echo "FILES=$FILES" >> $GITHUB_ENV
          
      - name: Test
        run: |
          export APPIMAGE_EXTRACT_AND_RUN=1
          echo "$FILES" ; if [ x"$FILES" == x ] ; then echo "Variable FILES is empty." && exit 1 ; fi
          xvfb-run --auto-servernum bash -e code/worker.sh $(readlink -f "$FILES") ;

      - name: Report success
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            @${{ github.actor }} Build completed with exit code
            \![]({{ env.SCREENSHOT_URL }})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

